name: lando-ruby-1
services:
  defaults:
    type: ruby:1.9

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/ruby": ./../../